from __future__ import annotations

import json
import re
import shutil
import subprocess
from collections.abc import Callable
from datetime import datetime, timezone
from pathlib import Path

from arl.config import Settings
from arl.copywriter.models import PublishingPackage
from arl.highlights.content_analyzer import analyze_content_density
from arl.highlights.cue_classifier import classify_cues
from arl.highlights.models import ClassifiedCue
from arl.highlights.service import (
    _HIGHLIGHT_KEYWORDS,
    _TACTICAL_KEYWORDS,
    HighlightPlannerService,
    condensed_duration_budget,
)
from arl.media.recording_resolver import recording_primary_video_path
from arl.shared.contracts import (
    CopyAsset,
    EditPlanAsset,
    ExportAsset,
    HighlightPlanAsset,
    MatchBoundary,
    SubtitleAsset,
    TimelineSegment,
)
from arl.shared.jsonl_store import load_models
from arl.shared.logging import log
from arl.subtitles.ass import SrtCue, parse_srt_cues
from arl.subtitles.retime import (
    retime_srt_cues_for_edit_plan,
    retime_srt_cues_for_highlight_plan,
)

from arl.quality_report.models import (
    BgmBedMetric,
    CopyMetric,
    MediaProbeResult,
    NoSubtitleGap,
    QualityReportResult,
    QualityReportRow,
    QualityWarning,
    SfxHitMetric,
    TargetDurationMetric,
    ZoomSegmentMetric,
)


MediaProbe = Callable[[Path], MediaProbeResult]
KdaEventProvider = Callable[[MatchBoundary], list[ClassifiedCue]]

_KEY_EVENT_COVERAGE_REASONS = {"condensed_key_event", "highlight_keyword"}
_PLACEHOLDER_SUBTITLE_MARKER = "placeholder subtitle generated by local pipeline"
_SECONDS_EPSILON = 0.001


class QualityReportService:
    def __init__(
        self,
        settings: Settings,
        *,
        media_probe: MediaProbe | None = None,
        kda_event_provider: KdaEventProvider | None = None,
    ) -> None:
        self.settings = settings
        self.media_probe = media_probe or self._probe_media
        self.kda_event_provider = kda_event_provider
        self.boundaries_path = settings.storage.temp_dir / "match-boundaries.jsonl"
        self.subtitles_path = settings.storage.temp_dir / "subtitle-assets.jsonl"
        self.highlight_plans_path = settings.storage.temp_dir / "highlight-plans.jsonl"
        self.edit_plans_path = settings.storage.temp_dir / "edit-plans.jsonl"
        self.exports_path = settings.storage.temp_dir / "export-assets.jsonl"
        self.copy_assets_path = settings.storage.temp_dir / "copy-assets.jsonl"
        self.packages_path = settings.storage.temp_dir / "publishing-packages.jsonl"
        self._highlight_service: HighlightPlannerService | None = None

    def run(
        self,
        *,
        session_ids: set[str] | None = None,
        match_indices: set[int] | None = None,
        all_latest: bool = False,
        strict: bool = False,
        top_gaps: int | None = None,
    ) -> QualityReportResult:
        log("quality-report", "starting")
        selected_exports = self._select_exports(
            session_ids=session_ids,
            match_indices=match_indices,
            all_latest=all_latest,
        )
        boundaries = self._latest_by_key(load_models(self.boundaries_path, MatchBoundary))
        subtitles = self._latest_by_key(load_models(self.subtitles_path, SubtitleAsset))
        highlight_plans = self._latest_by_key(
            load_models(self.highlight_plans_path, HighlightPlanAsset)
        )
        edit_plans = self._latest_by_key(load_models(self.edit_plans_path, EditPlanAsset))
        copy_assets = self._latest_by_key(load_models(self.copy_assets_path, CopyAsset))
        packages = self._latest_by_key(load_models(self.packages_path, PublishingPackage))

        gap_limit = top_gaps or self.settings.quality_report.top_no_subtitle_gaps
        rows = [
            self._build_row(
                export=export,
                boundary=boundaries.get((export.session_id, export.match_index)),
                subtitle=subtitles.get((export.session_id, export.match_index)),
                highlight_plan=highlight_plans.get((export.session_id, export.match_index)),
                edit_plan=edit_plans.get((export.session_id, export.match_index)),
                copy_asset=copy_assets.get((export.session_id, export.match_index)),
                package=packages.get((export.session_id, export.match_index)),
                top_gaps=gap_limit,
            )
            for export in selected_exports
        ]
        rows = [self._write_report_files(row) for row in rows]
        markdown = self._format_markdown(rows)
        has_warnings = any(row.warnings for row in rows)
        exit_code = 1 if strict and has_warnings else 0
        log(
            "quality-report",
            f"reports={len(rows)} warnings={sum(len(row.warnings) for row in rows)}",
        )
        return QualityReportResult(
            generated_at=datetime.now(timezone.utc),
            strict=strict,
            exit_code=exit_code,
            rows=rows,
            markdown=markdown,
        )

    def _select_exports(
        self,
        *,
        session_ids: set[str] | None,
        match_indices: set[int] | None,
        all_latest: bool,
    ) -> list[ExportAsset]:
        exports = load_models(self.exports_path, ExportAsset)
        filtered: list[ExportAsset] = []
        for export in exports:
            if session_ids is not None and export.session_id not in session_ids:
                continue
            if match_indices is not None and export.match_index not in match_indices:
                continue
            filtered.append(export)
        latest = list(self._latest_by_key(filtered).values())
        if all_latest:
            return latest
        return latest

    def _build_row(
        self,
        *,
        export: ExportAsset,
        boundary: MatchBoundary | None,
        subtitle: SubtitleAsset | None,
        highlight_plan: HighlightPlanAsset | None,
        edit_plan: EditPlanAsset | None,
        copy_asset: CopyAsset | None,
        package: PublishingPackage | None,
        top_gaps: int,
    ) -> QualityReportRow:
        warnings: list[QualityWarning] = []
        export_path = Path(export.path)
        media = self._safe_probe_media(export_path, warnings)
        subtitle_path = Path(export.subtitle_path) if export.subtitle_path else None
        if subtitle_path is None and subtitle is not None:
            subtitle_path = Path(subtitle.path)

        source_cues = self._load_subtitle_cues(subtitle_path, warnings)
        retimed_cues = self._retimed_cues(
            source_cues,
            edit_plan=edit_plan,
            highlight_plan=highlight_plan,
            warnings=warnings,
        )
        plan_duration_seconds = self._plan_duration(edit_plan, highlight_plan, boundary)
        main_duration_seconds = self._main_duration(edit_plan, highlight_plan)
        boundary_duration_seconds = (
            max(0.0, boundary.ended_at_seconds - boundary.started_at_seconds)
            if boundary is not None
            else None
        )
        timeline_duration_seconds = (
            media.duration_seconds
            or plan_duration_seconds
            or boundary_duration_seconds
            or 0.0
        )
        (
            subtitle_active_ratio,
            subtitle_covered_seconds,
            gaps,
            no_subtitle_gap_count,
            max_no_subtitle_gap,
        ) = self._subtitle_metrics(
            retimed_cues,
            timeline_duration_seconds,
            top_gaps=top_gaps,
            long_gap_min_seconds=(
                self.settings.quality_report.long_no_subtitle_gap_min_seconds
            ),
        )
        source_gaps = self._source_gaps(edit_plan, highlight_plan)
        max_source_gap = max(source_gaps) if source_gaps else 0.0
        kda_events, kda_error = self._kda_events(boundary)
        if kda_error is not None:
            warnings.append(
                QualityWarning(
                    code="kda_detection_failed",
                    message="KDA event detection failed.",
                    value=kda_error,
                )
            )
        coverage_windows = self._key_event_coverage_windows(edit_plan, highlight_plan)
        kda_uncovered = self._kda_uncovered_count(kda_events, coverage_windows)
        target = self._target_duration(boundary, source_cues, kda_events)
        # Prefer the target the planner actually used (persisted on the plan
        # asset) over the report-time recompute, so budget checks cannot drift
        # when config changed between the plan run and the report run.
        if (
            highlight_plan is not None
            and highlight_plan.target_duration_seconds is not None
        ):
            target = target.model_copy(
                update={
                    "target_duration_seconds": highlight_plan.target_duration_seconds
                }
            )
        duration_budget = self._duration_budget(
            highlight_plan,
            target,
            boundary_duration_seconds,
        )
        budget_exception_reason = (
            highlight_plan.budget_exception_reason
            if highlight_plan is not None
            else None
        )
        teaser_count, teaser_seconds = self._teaser_metrics(edit_plan)
        bgm_beds = self._bgm_metrics(edit_plan)
        sfx_hits = self._sfx_metrics(edit_plan, kda_events)
        zoom_segments = self._zoom_metrics(edit_plan)
        copywriter = self._copy_metric(
            copy_asset=copy_asset,
            package=package,
            cues=source_cues,
        )

        row = QualityReportRow(
            session_id=export.session_id,
            match_index=export.match_index,
            export_path=str(export_path),
            subtitle_path=str(subtitle_path) if subtitle_path is not None else None,
            export_duration_seconds=media.duration_seconds,
            container_bitrate_kbps=media.bitrate_kbps,
            width=media.width,
            height=media.height,
            condensed_target=target,
            condensed_target_range_seconds=(
                float(self.settings.highlights.condensed_target_duration_range[0]) * 60.0,
                float(self.settings.highlights.condensed_target_duration_range[1]) * 60.0,
            ),
            plan_duration_seconds=plan_duration_seconds,
            main_duration_seconds=main_duration_seconds,
            duration_budget_seconds=duration_budget,
            budget_exception_reason=budget_exception_reason,
            boundary_duration_seconds=boundary_duration_seconds,
            max_source_gap_seconds=max_source_gap,
            subtitle_active_ratio=subtitle_active_ratio,
            subtitle_covered_seconds=subtitle_covered_seconds,
            no_subtitle_gap_count=no_subtitle_gap_count,
            long_no_subtitle_gap_min_seconds=(
                self.settings.quality_report.long_no_subtitle_gap_min_seconds
            ),
            max_no_subtitle_gap_seconds=max_no_subtitle_gap,
            longest_no_subtitle_gaps=gaps,
            kda_event_count=len(kda_events),
            kda_uncovered_count=kda_uncovered,
            teaser_segment_count=teaser_count,
            teaser_total_seconds=teaser_seconds,
            bgm_beds=bgm_beds,
            sfx_hits=sfx_hits,
            zoom_segments=zoom_segments,
            copywriter=copywriter,
            warnings=warnings,
        )
        return row.model_copy(update={"warnings": [*warnings, *self._threshold_warnings(row)]})

    def _safe_probe_media(
        self,
        export_path: Path,
        warnings: list[QualityWarning],
    ) -> MediaProbeResult:
        if not export_path.exists():
            warnings.append(
                QualityWarning(
                    code="export_file_missing",
                    message="Export file does not exist.",
                    value=str(export_path),
                )
            )
            return MediaProbeResult(probe_error="export_file_missing")
        try:
            media = self.media_probe(export_path)
        except Exception as exc:
            media = MediaProbeResult(probe_error=exc.__class__.__name__)
        if media.probe_error is not None:
            warnings.append(
                QualityWarning(
                    code="media_probe_failed",
                    message="Could not read export media metadata.",
                    value=media.probe_error,
                )
            )
        return media

    def _load_subtitle_cues(
        self,
        subtitle_path: Path | None,
        warnings: list[QualityWarning],
    ) -> list[SrtCue]:
        if subtitle_path is None:
            warnings.append(
                QualityWarning(
                    code="subtitle_asset_missing",
                    message="No subtitle asset is available for this export.",
                )
            )
            return []
        if not subtitle_path.exists():
            warnings.append(
                QualityWarning(
                    code="subtitle_file_missing",
                    message="Subtitle file does not exist.",
                    value=str(subtitle_path),
                )
            )
            return []
        try:
            return parse_srt_cues(subtitle_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError) as exc:
            warnings.append(
                QualityWarning(
                    code="subtitle_parse_failed",
                    message="Subtitle file could not be parsed.",
                    value=exc.__class__.__name__,
                )
            )
            return []

    def _retimed_cues(
        self,
        source_cues: list[SrtCue],
        *,
        edit_plan: EditPlanAsset | None,
        highlight_plan: HighlightPlanAsset | None,
        warnings: list[QualityWarning],
    ) -> list[SrtCue]:
        if not source_cues:
            return []
        try:
            if edit_plan is not None:
                return retime_srt_cues_for_edit_plan(source_cues, edit_plan)
            if highlight_plan is not None:
                return retime_srt_cues_for_highlight_plan(source_cues, highlight_plan)
        except Exception as exc:
            warnings.append(
                QualityWarning(
                    code="subtitle_retime_failed",
                    message="Subtitle cues could not be retimed through the plan.",
                    value=exc.__class__.__name__,
                )
            )
            return []
        return source_cues

    def _subtitle_metrics(
        self,
        cues: list[SrtCue],
        duration_seconds: float,
        *,
        top_gaps: int,
        long_gap_min_seconds: float,
    ) -> tuple[float, float, list[NoSubtitleGap], int, float]:
        if duration_seconds <= 0.0:
            return 0.0, 0.0, [], 0, 0.0
        intervals = [
            (
                max(0.0, min(duration_seconds, cue.started_at_seconds)),
                max(0.0, min(duration_seconds, cue.ended_at_seconds)),
            )
            for cue in cues
        ]
        intervals = [(start, end) for start, end in intervals if end - start > 0.0]
        merged = self._merge_intervals(intervals)
        covered = sum(end - start for start, end in merged)
        gaps: list[NoSubtitleGap] = []
        cursor = 0.0
        for start, end in merged:
            if start - cursor > _SECONDS_EPSILON:
                gaps.append(
                    NoSubtitleGap(
                        start_seconds=round(cursor, 3),
                        end_seconds=round(start, 3),
                        duration_seconds=round(start - cursor, 3),
                    )
                )
            cursor = max(cursor, end)
        if duration_seconds - cursor > _SECONDS_EPSILON:
            gaps.append(
                NoSubtitleGap(
                    start_seconds=round(cursor, 3),
                    end_seconds=round(duration_seconds, 3),
                    duration_seconds=round(duration_seconds - cursor, 3),
                )
            )
        gaps.sort(key=lambda gap: (-gap.duration_seconds, gap.start_seconds))
        long_gaps = [
            gap for gap in gaps if gap.duration_seconds >= long_gap_min_seconds
        ]
        return (
            min(1.0, covered / duration_seconds),
            covered,
            gaps[:top_gaps],
            len(long_gaps),
            max((gap.duration_seconds for gap in gaps), default=0.0),
        )

    @staticmethod
    def _merge_intervals(intervals: list[tuple[float, float]]) -> list[tuple[float, float]]:
        merged: list[tuple[float, float]] = []
        for start, end in sorted(intervals):
            if not merged or start > merged[-1][1] + _SECONDS_EPSILON:
                merged.append((start, end))
                continue
            previous_start, previous_end = merged[-1]
            merged[-1] = (previous_start, max(previous_end, end))
        return merged

    def _kda_events(
        self,
        boundary: MatchBoundary | None,
    ) -> tuple[list[ClassifiedCue], str | None]:
        if boundary is None:
            return [], None
        if self.kda_event_provider is not None:
            return self.kda_event_provider(boundary), None
        duration = max(0.0, boundary.ended_at_seconds - boundary.started_at_seconds)
        if duration <= 0.0:
            return [], None
        try:
            service = self._get_highlight_service()
            recording = service._find_recording_asset(boundary)
            return (
                service._detect_kda_event_cues(
                    recording=recording,
                    boundary=boundary,
                    duration=duration,
                ),
                None,
            )
        except Exception as exc:
            return [], exc.__class__.__name__

    def _target_duration(
        self,
        boundary: MatchBoundary | None,
        cues: list[SrtCue],
        kda_events: list[ClassifiedCue],
    ) -> TargetDurationMetric:
        if boundary is None:
            return TargetDurationMetric()
        duration = max(0.0, boundary.ended_at_seconds - boundary.started_at_seconds)
        if duration <= 0.0:
            return TargetDurationMetric()
        meaningful_cues = [
            cue for cue in cues if _PLACEHOLDER_SUBTITLE_MARKER not in cue.text.lower()
        ]
        if not meaningful_cues and not kda_events:
            return TargetDurationMetric()
        classified = classify_cues(
            cues=[
                (cue.started_at_seconds, cue.ended_at_seconds, cue.text)
                for cue in meaningful_cues
                if cue.started_at_seconds < duration
            ],
            highlight_keywords=_HIGHLIGHT_KEYWORDS,
            tactical_keywords=(
                _TACTICAL_KEYWORDS
                + tuple(
                    keyword.lower()
                    for keyword in self.settings.highlights.custom_tactical_keywords
                )
            ),
            low_value_min_length=(
                self.settings.highlights.condensed_low_value_min_length
            ),
            low_value_similarity_threshold=(
                self.settings.highlights.condensed_low_value_similarity_threshold
            ),
            low_value_repeat_window_seconds=(
                self.settings.highlights.condensed_low_value_repeat_window_seconds
            ),
        )
        classified.extend(kda_events)
        video_path = self._target_video_path(boundary) if classified else None
        density = analyze_content_density(
            classified_cues=classified,
            match_duration_seconds=duration,
            video_path=video_path,
            weight_highlight_events=(
                self.settings.highlights.condensed_weight_highlight_events
            ),
            weight_narration=self.settings.highlights.condensed_weight_narration,
            weight_visual=self.settings.highlights.condensed_weight_visual,
            weight_baseline=self.settings.highlights.condensed_weight_baseline,
            use_visual_analysis=(
                self.settings.highlights.condensed_use_visual_analysis
                and video_path is not None
            ),
            visual_sample_interval=(
                self.settings.highlights.condensed_visual_sample_interval_seconds
            ),
            high_density_threshold=(
                self.settings.highlights.condensed_high_density_threshold
            ),
            low_density_threshold=self.settings.highlights.condensed_low_density_threshold,
            high_density_duration_range=(
                self.settings.highlights.condensed_high_density_duration_range
            ),
            mid_density_duration_range=(
                self.settings.highlights.condensed_mid_density_duration_range
            ),
            low_density_duration_range=(
                self.settings.highlights.condensed_low_density_duration_range
            ),
        )
        return TargetDurationMetric(
            target_duration_seconds=density.target_duration_seconds,
            content_density_score=density.content_density_score,
            highlight_event_density=density.highlight_event_density,
            narration_density=density.narration_density,
            visual_activity=density.visual_activity,
        )

    @staticmethod
    def _duration_budget(
        highlight_plan: HighlightPlanAsset | None,
        target: TargetDurationMetric,
        boundary_duration_seconds: float | None,
    ) -> float | None:
        if highlight_plan is not None and highlight_plan.budget_seconds is not None:
            return highlight_plan.budget_seconds
        if (
            target.target_duration_seconds is None
            or boundary_duration_seconds is None
            or boundary_duration_seconds <= 0.0
        ):
            return None
        return round(
            condensed_duration_budget(
                target.target_duration_seconds,
                boundary_duration_seconds,
            ),
            3,
        )

    def _target_video_path(self, boundary: MatchBoundary) -> Path | None:
        try:
            recording = self._get_highlight_service()._find_recording_asset(boundary)
            if recording is None:
                return None
            path = recording_primary_video_path(recording)
            return path if path is not None and path.exists() else None
        except Exception:
            return None

    def _source_gaps(
        self,
        edit_plan: EditPlanAsset | None,
        highlight_plan: HighlightPlanAsset | None,
    ) -> list[float]:
        if edit_plan is not None:
            windows = [
                (segment.source_start_seconds, segment.source_end_seconds)
                for segment in edit_plan.timeline
                if segment.role != "teaser"
            ]
        elif highlight_plan is not None:
            windows = [
                (window.started_at_seconds, window.ended_at_seconds)
                for window in highlight_plan.windows
            ]
        else:
            return []
        gaps: list[float] = []
        previous_end: float | None = None
        for start, end in sorted(windows):
            if previous_end is not None and start > previous_end:
                gaps.append(start - previous_end)
            previous_end = max(previous_end or end, end)
        return gaps

    def _key_event_coverage_windows(
        self,
        edit_plan: EditPlanAsset | None,
        highlight_plan: HighlightPlanAsset | None,
    ) -> list[tuple[float, float]]:
        if edit_plan is not None:
            windows = [
                (segment.source_start_seconds, segment.source_end_seconds)
                for segment in edit_plan.timeline
                if segment.reason in _KEY_EVENT_COVERAGE_REASONS
            ]
        elif highlight_plan is not None:
            windows = [
                (window.started_at_seconds, window.ended_at_seconds)
                for window in highlight_plan.windows
                if window.reason in _KEY_EVENT_COVERAGE_REASONS
            ]
        else:
            return []
        # Close-up zoom splits one retained key-event span into adjacent
        # timeline pieces around the kill timestamp; coverage is judged on the
        # merged source-time span, not on any single piece.
        return self._merge_adjacent_windows(windows)

    @staticmethod
    def _merge_adjacent_windows(
        windows: list[tuple[float, float]],
    ) -> list[tuple[float, float]]:
        merged: list[tuple[float, float]] = []
        for start, end in sorted(windows):
            if merged and start <= merged[-1][1] + _SECONDS_EPSILON:
                merged[-1] = (merged[-1][0], max(merged[-1][1], end))
                continue
            merged.append((start, end))
        return merged

    @staticmethod
    def _kda_uncovered_count(
        kda_events: list[ClassifiedCue],
        coverage_windows: list[tuple[float, float]],
    ) -> int:
        uncovered = 0
        for cue in kda_events:
            if not cue.text.startswith("kda_change "):
                continue
            if any(
                start <= cue.started_at_seconds + _SECONDS_EPSILON
                and end >= cue.ended_at_seconds - _SECONDS_EPSILON
                for start, end in coverage_windows
            ):
                continue
            uncovered += 1
        return uncovered

    @staticmethod
    def _plan_duration(
        edit_plan: EditPlanAsset | None,
        highlight_plan: HighlightPlanAsset | None,
        boundary: MatchBoundary | None,
    ) -> float | None:
        if edit_plan is not None:
            return sum(
                QualityReportService._timeline_segment_duration(segment)
                for segment in edit_plan.timeline
            )
        if highlight_plan is not None:
            return sum(
                max(0.0, window.ended_at_seconds - window.started_at_seconds)
                for window in highlight_plan.windows
            )
        if boundary is None:
            return None
        return max(0.0, boundary.ended_at_seconds - boundary.started_at_seconds)

    @staticmethod
    def _main_duration(
        edit_plan: EditPlanAsset | None,
        highlight_plan: HighlightPlanAsset | None,
    ) -> float | None:
        """Condensed main-content duration, excluding teaser/transition roles.

        The duration budget governs condensed retention; the teaser cold open
        re-plays retained content and has its own dynamic budget, so it must
        not count against the plan budget.
        """
        if edit_plan is not None:
            return sum(
                QualityReportService._timeline_segment_duration(segment)
                for segment in edit_plan.timeline
                if segment.role == "main"
            )
        if highlight_plan is not None:
            return sum(
                max(0.0, window.ended_at_seconds - window.started_at_seconds)
                for window in highlight_plan.windows
            )
        return None

    @staticmethod
    def _teaser_metrics(edit_plan: EditPlanAsset | None) -> tuple[int, float]:
        if edit_plan is None:
            return 0, 0.0
        teaser_segments = [
            segment for segment in edit_plan.timeline if segment.role == "teaser"
        ]
        # Zoom close-ups split one teaser span into multiple timeline
        # segments; count distinct source spans (adjacent segments merged),
        # mirroring the KDA coverage merge.
        distinct_spans = 0
        previous_end: float | None = None
        for segment in teaser_segments:
            if (
                previous_end is None
                or abs(segment.source_start_seconds - previous_end) > 0.05
            ):
                distinct_spans += 1
            previous_end = segment.source_end_seconds
        return (
            distinct_spans,
            sum(
                QualityReportService._timeline_segment_duration(segment)
                for segment in teaser_segments
            ),
        )

    @staticmethod
    def _bgm_metrics(edit_plan: EditPlanAsset | None) -> list[BgmBedMetric]:
        if edit_plan is None:
            return []
        return [
            BgmBedMetric(
                source_path=bed.source_path,
                timeline_start_seconds=bed.timeline_start_seconds,
                timeline_end_seconds=bed.timeline_end_seconds,
                reason=bed.reason,
            )
            for bed in edit_plan.audio_beds
        ]

    def _sfx_metrics(
        self,
        edit_plan: EditPlanAsset | None,
        kda_events: list[ClassifiedCue],
    ) -> list[SfxHitMetric]:
        if edit_plan is None:
            return []
        kda_timestamps = [self._kda_event_timestamp(cue) for cue in kda_events]
        kda_timestamps = [value for value in kda_timestamps if value is not None]
        metrics: list[SfxHitMetric] = []
        for hit in edit_plan.sound_effects:
            source_timestamp = self._output_to_source_seconds(edit_plan, hit.at_seconds)
            nearest_delta = None
            if source_timestamp is not None and kda_timestamps:
                nearest_delta = min(
                    abs(source_timestamp - timestamp) for timestamp in kda_timestamps
                )
            metrics.append(
                SfxHitMetric(
                    source_path=hit.source_path,
                    at_seconds=hit.at_seconds,
                    reason=hit.reason,
                    source_timestamp_seconds=source_timestamp,
                    nearest_kda_delta_seconds=nearest_delta,
                )
            )
        return metrics

    @staticmethod
    def _zoom_metrics(edit_plan: EditPlanAsset | None) -> list[ZoomSegmentMetric]:
        if edit_plan is None:
            return []
        metrics: list[ZoomSegmentMetric] = []
        output_cursor = 0.0
        for segment in edit_plan.timeline:
            duration = QualityReportService._timeline_segment_duration(segment)
            transform = segment.transform
            if transform is not None and transform.kind == "punch_in":
                metrics.append(
                    ZoomSegmentMetric(
                        role=segment.role,
                        source_start_seconds=segment.source_start_seconds,
                        source_end_seconds=segment.source_end_seconds,
                        output_start_seconds=round(output_cursor, 3),
                        duration_seconds=duration,
                        target=transform.target,
                    )
                )
            output_cursor += duration
        return metrics

    def _copy_metric(
        self,
        *,
        copy_asset: CopyAsset | None,
        package: PublishingPackage | None,
        cues: list[SrtCue],
    ) -> CopyMetric:
        title = None
        cover_lines: list[str] = []
        if package is not None:
            title = package.recommended_title
            cover_lines = list(package.cover_lines)
        elif copy_asset is not None:
            title = copy_asset.title
        return CopyMetric(
            title=title,
            cover_lines=cover_lines,
            title_equals_raw_leading_subtitle=self._title_equals_leading_subtitle(
                title,
                cues,
            ),
        )

    def _threshold_warnings(self, row: QualityReportRow) -> list[QualityWarning]:
        thresholds = self.settings.quality_report
        warnings: list[QualityWarning] = []
        if (
            thresholds.duration_budget_enforced
            and row.main_duration_seconds is not None
            and row.duration_budget_seconds is not None
            and row.main_duration_seconds > row.duration_budget_seconds + 1.0
            and row.budget_exception_reason is None
        ):
            warnings.append(
                QualityWarning(
                    code="plan_duration_above_budget",
                    message=(
                        "Condensed main duration exceeds the duration budget "
                        "without a recorded exception."
                    ),
                    value=round(row.main_duration_seconds, 1),
                    threshold=round(row.duration_budget_seconds, 1),
                )
            )
        if row.subtitle_active_ratio < thresholds.subtitle_active_ratio_min:
            warnings.append(
                QualityWarning(
                    code="subtitle_active_ratio_below_min",
                    message="Subtitle active ratio is below the configured minimum.",
                    value=round(row.subtitle_active_ratio, 4),
                    threshold=thresholds.subtitle_active_ratio_min,
                )
            )
        if row.max_source_gap_seconds > thresholds.max_source_gap_seconds:
            warnings.append(
                QualityWarning(
                    code="max_source_gap_above_limit",
                    message="A retained-plan source-time gap exceeds the configured limit.",
                    value=round(row.max_source_gap_seconds, 3),
                    threshold=thresholds.max_source_gap_seconds,
                )
            )
        if not (
            thresholds.teaser_min_segments
            <= row.teaser_segment_count
            <= thresholds.teaser_max_segments
        ):
            warnings.append(
                QualityWarning(
                    code="teaser_segment_count_out_of_range",
                    message="Teaser segment count is outside the configured range.",
                    value=row.teaser_segment_count,
                    threshold=[
                        thresholds.teaser_min_segments,
                        thresholds.teaser_max_segments,
                    ],
                )
            )
        # Transition whoosh and teaser-impact hits are accents outside the
        # kill rate limit; only kill-accent hits count against the maximum.
        kill_sfx_count = sum(
            1
            for hit in row.sfx_hits
            if not hit.reason.startswith("transition")
            and hit.reason != "teaser_impact"
        )
        if kill_sfx_count > thresholds.sfx_max_hits:
            warnings.append(
                QualityWarning(
                    code="sfx_hit_count_above_limit",
                    message="SFX hit count exceeds the configured maximum.",
                    value=kill_sfx_count,
                    threshold=thresholds.sfx_max_hits,
                )
            )
        if not (
            thresholds.zoom_min_segments
            <= len(row.zoom_segments)
            <= thresholds.zoom_max_segments
        ):
            warnings.append(
                QualityWarning(
                    code="zoom_segment_count_out_of_range",
                    message="Zoom segment count is outside the configured range.",
                    value=len(row.zoom_segments),
                    threshold=[
                        thresholds.zoom_min_segments,
                        thresholds.zoom_max_segments,
                    ],
                )
            )
        return warnings

    def _write_report_files(self, row: QualityReportRow) -> QualityReportRow:
        output_dir = self.settings.storage.processed_dir / row.session_id / "reports"
        output_dir.mkdir(parents=True, exist_ok=True)
        json_path = output_dir / f"match-{row.match_index:02d}-quality-report.json"
        markdown_path = output_dir / f"match-{row.match_index:02d}-quality-report.md"
        row = row.model_copy(
            update={
                "report_json_path": str(json_path),
                "report_markdown_path": str(markdown_path),
            }
        )
        json_path.write_text(
            json.dumps(row.model_dump(mode="json"), ensure_ascii=False, indent=2)
            + "\n",
            encoding="utf-8",
        )
        markdown_path.write_text(
            self._format_markdown([row], include_details=True),
            encoding="utf-8",
        )
        return row

    def _format_markdown(
        self,
        rows: list[QualityReportRow],
        *,
        include_details: bool = False,
    ) -> str:
        if not rows:
            return "## Quality Report\n\nNo exports matched the selected filters.\n"
        lines = [
            "## Quality Report",
            "",
            (
                "| Sample | Export min | Bitrate | Res | Target min | Budget min | "
                "Plan min | "
                "Max source gap | KDA uncovered | Subtitle active | No-sub gaps | "
                "Teaser | BGM | SFX | Zoom | Warnings |"
            ),
            "|---|---:|---:|---|---:|---:|---:|---:|---:|---:|---|---:|---:|---:|---:|---:|",
        ]
        for row in rows:
            lines.append(self._markdown_row(row))
        if include_details:
            for row in rows:
                lines.extend(self._detail_lines(row))
        return "\n".join(lines).rstrip() + "\n"

    def _markdown_row(self, row: QualityReportRow) -> str:
        resolution = (
            f"{row.width}x{row.height}"
            if row.width is not None and row.height is not None
            else "-"
        )
        max_gap = (
            f"{row.no_subtitle_gap_count}, max {row.max_no_subtitle_gap_seconds:.1f}s"
            if row.no_subtitle_gap_count
            else "0"
        )
        return (
            f"| `{row.session_id}` m{row.match_index:02d} "
            f"| {self._minutes(row.export_duration_seconds)} "
            f"| {self._mbps(row.container_bitrate_kbps)} "
            f"| {resolution} "
            f"| {self._minutes(row.condensed_target.target_duration_seconds)} "
            f"| {self._minutes(row.duration_budget_seconds)} "
            f"| {self._minutes(row.plan_duration_seconds)} "
            f"| {row.max_source_gap_seconds:.1f}s "
            f"| {row.kda_uncovered_count}/{row.kda_event_count} "
            f"| {row.subtitle_active_ratio * 100:.1f}% "
            f"| {max_gap} "
            f"| {row.teaser_segment_count} "
            f"| {len(row.bgm_beds)} "
            f"| {len(row.sfx_hits)} "
            f"| {len(row.zoom_segments)} "
            f"| {len(row.warnings)} |"
        )

    def _detail_lines(self, row: QualityReportRow) -> list[str]:
        lines = [
            "",
            f"### `{row.session_id}` m{row.match_index:02d}",
            "",
            f"- Export: `{row.export_path}`",
            f"- JSON: `{row.report_json_path}`",
        ]
        if row.warnings:
            lines.append("- Warnings: " + ", ".join(warning.code for warning in row.warnings))
        if row.budget_exception_reason:
            lines.append(
                f"- Duration budget exception: {row.budget_exception_reason}"
            )
        if row.longest_no_subtitle_gaps:
            lines.append(
                "- Longest no-subtitle gaps: "
                + ", ".join(
                    (
                        f"{self._timestamp(gap.start_seconds)}-"
                        f"{self._timestamp(gap.end_seconds)} "
                        f"({gap.duration_seconds:.1f}s)"
                    )
                    for gap in row.longest_no_subtitle_gaps
                )
            )
        if row.bgm_beds:
            lines.append(
                "- BGM switches: "
                + ", ".join(
                    f"{self._timestamp(bed.timeline_start_seconds)} `{bed.source_path}`"
                    for bed in row.bgm_beds
                )
            )
        if row.sfx_hits:
            lines.append(
                "- SFX hits: "
                + ", ".join(self._sfx_detail(hit) for hit in row.sfx_hits)
            )
        if row.zoom_segments:
            lines.append(
                "- Zoom segments: "
                + ", ".join(
                    (
                        f"{self._timestamp(item.output_start_seconds)} "
                        f"{item.duration_seconds:.1f}s"
                    )
                    for item in row.zoom_segments
                )
            )
        if row.copywriter.title:
            lines.append(f"- Title: {row.copywriter.title}")
        if row.copywriter.cover_lines:
            lines.append("- Cover lines: " + " / ".join(row.copywriter.cover_lines))
        return lines

    def _sfx_detail(self, hit: SfxHitMetric) -> str:
        detail = self._timestamp(hit.at_seconds)
        if hit.nearest_kda_delta_seconds is not None:
            detail = f"{detail} delta={hit.nearest_kda_delta_seconds:.1f}s"
        return detail

    @staticmethod
    def _minutes(seconds: float | None) -> str:
        if seconds is None:
            return "-"
        return f"{seconds / 60.0:.2f}"

    @staticmethod
    def _mbps(kbps: float | None) -> str:
        if kbps is None:
            return "-"
        return f"{kbps / 1000.0:.2f}"

    @staticmethod
    def _timestamp(seconds: float) -> str:
        whole = max(0, int(seconds))
        minutes, secs = divmod(whole, 60)
        return f"{minutes:02d}:{secs:02d}"

    @staticmethod
    def _title_equals_leading_subtitle(
        title: str | None,
        cues: list[SrtCue],
    ) -> bool:
        if not title:
            return False
        normalized_title = QualityReportService._normalize_copy_text(title)
        leading = [
            cue.text
            for cue in cues
            if _PLACEHOLDER_SUBTITLE_MARKER not in cue.text.lower()
        ][:5]
        candidates = [QualityReportService._normalize_copy_text(text) for text in leading]
        for count in range(2, min(4, len(leading) + 1)):
            candidates.append(
                QualityReportService._normalize_copy_text(" ".join(leading[:count]))
            )
        return normalized_title in {candidate for candidate in candidates if candidate}

    @staticmethod
    def _normalize_copy_text(value: str) -> str:
        return re.sub(r"\s+", " ", value.strip()).strip(" .!?;:").lower()

    @staticmethod
    def _output_to_source_seconds(
        edit_plan: EditPlanAsset,
        output_seconds: float,
    ) -> float | None:
        output_cursor = 0.0
        for segment in edit_plan.timeline:
            duration = QualityReportService._timeline_segment_duration(segment)
            if segment.role == "transition":
                output_cursor += duration
                continue
            if output_seconds <= output_cursor + duration + _SECONDS_EPSILON:
                offset = min(max(0.0, output_seconds - output_cursor), duration)
                return segment.source_start_seconds + offset
            output_cursor += duration
        return None

    @staticmethod
    def _timeline_segment_duration(segment) -> float:
        if segment.role == "transition":
            return max(0.0, segment.duration_seconds or 0.0)
        return max(0.0, segment.source_end_seconds - segment.source_start_seconds)

    @staticmethod
    def _kda_event_timestamp(cue: ClassifiedCue) -> float | None:
        match = re.search(r"\bcurrent_at=([0-9]+(?:\.[0-9]+)?)", cue.text)
        if match is not None:
            return float(match.group(1))
        if cue.ended_at_seconds > cue.started_at_seconds:
            return (cue.started_at_seconds + cue.ended_at_seconds) / 2.0
        return cue.started_at_seconds

    def _get_highlight_service(self) -> HighlightPlannerService:
        if self._highlight_service is None:
            self._highlight_service = HighlightPlannerService(self.settings)
        return self._highlight_service

    @staticmethod
    def _latest_by_key(items):
        latest = {}
        for item in items:
            latest[(item.session_id, item.match_index)] = item
        return latest

    @staticmethod
    def _probe_media(path: Path) -> MediaProbeResult:
        ffprobe_path = shutil.which("ffprobe")
        if ffprobe_path is None:
            return MediaProbeResult(probe_error="missing_ffprobe")
        command = [
            ffprobe_path,
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=width,height,bit_rate:format=duration,bit_rate,size",
            "-of",
            "json",
            str(path),
        ]
        try:
            result = subprocess.run(
                command,
                check=True,
                capture_output=True,
                text=True,
                timeout=30,
            )
        except (subprocess.SubprocessError, OSError) as exc:
            return MediaProbeResult(probe_error=exc.__class__.__name__)
        try:
            payload = json.loads(result.stdout or "{}")
        except json.JSONDecodeError:
            return MediaProbeResult(probe_error="invalid_ffprobe_json")

        stream = (payload.get("streams") or [{}])[0]
        format_payload = payload.get("format") or {}
        duration = _optional_float(format_payload.get("duration"))
        bit_rate = _optional_float(
            format_payload.get("bit_rate") or stream.get("bit_rate")
        )
        size = _optional_float(format_payload.get("size"))
        if bit_rate is None and size is not None and duration is not None and duration > 0:
            bit_rate = size * 8.0 / duration
        return MediaProbeResult(
            duration_seconds=duration,
            bitrate_kbps=(bit_rate / 1000.0 if bit_rate is not None else None),
            width=_optional_int(stream.get("width")),
            height=_optional_int(stream.get("height")),
        )


def _optional_float(value: object) -> float | None:
    try:
        if value is None or value == "":
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def _optional_int(value: object) -> int | None:
    try:
        if value is None or value == "":
            return None
        return int(value)
    except (TypeError, ValueError):
        return None
