from __future__ import annotations

import io
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

from arl.segmenter.stage_text import (
    classify_stage_from_text,
    default_stage_keywords,
    load_stage_keywords,
)
from arl.shared.contracts import MatchStage


class StageTextClassifierTest(unittest.TestCase):
    def test_classifies_english_stage_text(self) -> None:
        self.assertEqual(
            classify_stage_from_text("Champion Select draft is open."),
            MatchStage.CHAMPION_SELECT,
        )
        self.assertEqual(
            classify_stage_from_text("Game loading now."),
            MatchStage.LOADING,
        )
        self.assertEqual(
            classify_stage_from_text("In game scoreboard update."),
            MatchStage.IN_GAME,
        )
        self.assertEqual(
            classify_stage_from_text("Victory game over."),
            MatchStage.POST_GAME,
        )

    def test_classifies_chinese_stage_text(self) -> None:
        self.assertEqual(
            classify_stage_from_text("进入英雄选择，开始BP阶段。"),
            MatchStage.CHAMPION_SELECT,
        )
        self.assertEqual(
            classify_stage_from_text("正在加载中，准备就绪。"),
            MatchStage.LOADING,
        )
        self.assertEqual(
            classify_stage_from_text("对局中发生击杀并推塔。"),
            MatchStage.IN_GAME,
        )
        self.assertEqual(
            classify_stage_from_text("本局胜利，进入结算界面。"),
            MatchStage.POST_GAME,
        )

    def test_returns_none_for_unmatched_text(self) -> None:
        self.assertIsNone(classify_stage_from_text("Placeholder subtitle generated by local pipeline."))

    def test_accepts_custom_keyword_map(self) -> None:
        custom = default_stage_keywords()
        custom[MatchStage.IN_GAME] = ("laning phase",)
        custom[MatchStage.CHAMPION_SELECT] = ("draft-room",)
        custom[MatchStage.LOADING] = ("game-ready",)
        custom[MatchStage.POST_GAME] = ("final-whistle",)

        self.assertEqual(
            classify_stage_from_text("Draft_Room is open now.", custom),
            MatchStage.CHAMPION_SELECT,
        )
        self.assertEqual(
            classify_stage_from_text("Game-Ready and waiting.", custom),
            MatchStage.LOADING,
        )
        self.assertEqual(
            classify_stage_from_text("Laning phase reached.", custom),
            MatchStage.IN_GAME,
        )
        self.assertEqual(
            classify_stage_from_text("Final Whistle called.", custom),
            MatchStage.POST_GAME,
        )

    def test_load_stage_keywords_logs_missing_path_and_falls_back(self) -> None:
        missing = Path("/tmp/does-not-exist-stage-keywords.json")
        output = io.StringIO()
        with redirect_stdout(output):
            loaded = load_stage_keywords(missing, component="segmenter")

        self.assertIn("stage-keywords override path missing", output.getvalue())
        self.assertEqual(
            classify_stage_from_text("in game scoreboard", loaded),
            MatchStage.IN_GAME,
        )

    def test_load_stage_keywords_logs_invalid_json_and_falls_back(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            invalid_path = Path(tmp_dir) / "invalid-stage-keywords.json"
            invalid_path.write_text("{invalid-json", encoding="utf-8")

            output = io.StringIO()
            with redirect_stdout(output):
                loaded = load_stage_keywords(invalid_path, component="segmenter")

        self.assertIn("stage-keywords override invalid json", output.getvalue())
        self.assertEqual(
            classify_stage_from_text("victory game over", loaded),
            MatchStage.POST_GAME,
        )

    def test_load_stage_keywords_logs_invalid_stage_entry_and_keeps_default_for_that_stage(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            path = Path(tmp_dir) / "stage-keywords.json"
            path.write_text(
                (
                    '{\n'
                    '  "champion_select": "not-list",\n'
                    '  "loading": ["game ready"]\n'
                    "}\n"
                ),
                encoding="utf-8",
            )

            output = io.StringIO()
            with redirect_stdout(output):
                loaded = load_stage_keywords(path, component="segmenter")

        logs = output.getvalue()
        self.assertIn("stage-keywords override invalid stage entry stage=champion_select", logs)
        self.assertIn("stage-keywords override loaded", logs)
        self.assertEqual(
            classify_stage_from_text("Champion Select open", loaded),
            MatchStage.CHAMPION_SELECT,
        )
        self.assertEqual(
            classify_stage_from_text("Game Ready now", loaded),
            MatchStage.LOADING,
        )


if __name__ == "__main__":
    unittest.main()
