from __future__ import annotations

import json
import tempfile
import unittest
from contextlib import redirect_stdout
from datetime import datetime, timezone
from io import StringIO
from pathlib import Path

from arl.config import Settings, StorageSettings, SubtitleSettings
from arl.segmenter.models import MatchStageSignal
from arl.shared.contracts import MatchBoundary, RecordingAsset, SourceType
from arl.shared.jsonl_store import append_model, load_models
from arl.subtitles.service import SubtitleService


class _FakeSubtitleService(SubtitleService):
    def __init__(
        self,
        settings: Settings,
        entries: list[tuple[float, float, str]],
    ) -> None:
        super().__init__(settings)
        self._entries = entries

    def _transcribe_boundary(
        self,
        boundary: MatchBoundary,
        recording_path: str | None,
    ) -> list[tuple[float, float, str]]:
        return self._entries


def _read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        rows.append(json.loads(line))
    return rows


class SubtitleServiceTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        root = Path(self.temp_dir.name)
        self.temp_root = root / "tmp"
        self.raw_root = root / "raw"
        self.processed_root = root / "processed"
        self.export_root = root / "exports"
        self.boundaries_path = self.temp_root / "match-boundaries.jsonl"
        self.recording_assets_path = self.temp_root / "recording-assets.jsonl"
        self.subtitle_assets_path = self.temp_root / "subtitle-assets.jsonl"

        self.settings = Settings(
            storage=StorageSettings(
                raw_dir=self.raw_root,
                processed_dir=self.processed_root,
                export_dir=self.export_root,
                temp_dir=self.temp_root,
            ),
            subtitles=SubtitleSettings(enabled=True, provider="faster-whisper"),
        )

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def test_subtitle_service_falls_back_to_placeholder_for_unknown_provider(self) -> None:
        settings = self.settings.model_copy(deep=True)
        settings.subtitles.provider = "placeholder"
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-fallback",
                match_index=1,
                started_at_seconds=0.0,
                ended_at_seconds=30.0,
                confidence=0.8,
            ),
        )

        service = SubtitleService(settings)
        service.run()

        subtitle_assets = _read_jsonl(self.subtitle_assets_path)
        self.assertEqual(len(subtitle_assets), 1)
        subtitle_text = Path(subtitle_assets[0]["path"]).read_text(encoding="utf-8")
        self.assertIn("Placeholder subtitle generated by local pipeline.", subtitle_text)

        service.run()
        subtitle_assets = _read_jsonl(self.subtitle_assets_path)
        self.assertEqual(len(subtitle_assets), 1)

    def test_subtitle_service_writes_transcribed_srt_when_entries_available(self) -> None:
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-transcribe",
                match_index=2,
                started_at_seconds=10.0,
                ended_at_seconds=40.0,
                confidence=0.9,
            ),
        )
        recording_path = self.raw_root / "session-subtitle-transcribe" / "recording.mp4"
        recording_path.parent.mkdir(parents=True, exist_ok=True)
        recording_path.write_text("dummy media placeholder", encoding="utf-8")
        append_model(
            self.recording_assets_path,
            RecordingAsset(
                session_id="session-subtitle-transcribe",
                source_type=SourceType.BROWSER_CAPTURE,
                path=str(recording_path),
                started_at=datetime(2026, 4, 26, 9, 0, tzinfo=timezone.utc),
                ended_at=datetime(2026, 4, 26, 9, 30, tzinfo=timezone.utc),
            ),
        )

        service = _FakeSubtitleService(
            self.settings,
            entries=[
                (0.0, 1.25, "First subtitle line."),
                (1.25, 3.5, "Second subtitle line."),
            ],
        )
        service.run()

        subtitle_assets = _read_jsonl(self.subtitle_assets_path)
        self.assertEqual(len(subtitle_assets), 1)
        subtitle_text = Path(subtitle_assets[0]["path"]).read_text(encoding="utf-8")
        self.assertIn("00:00:00,000 --> 00:00:01,250", subtitle_text)
        self.assertIn("00:00:01,250 --> 00:00:03,500", subtitle_text)
        self.assertIn("First subtitle line.", subtitle_text)
        self.assertIn("Second subtitle line.", subtitle_text)
        self.assertNotIn("Placeholder subtitle generated by local pipeline.", subtitle_text)

    def test_subtitle_service_auto_extracts_stage_signals_from_generated_srt(self) -> None:
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-signal-001",
                match_index=1,
                started_at_seconds=0.0,
                ended_at_seconds=600.0,
                confidence=0.95,
            ),
        )
        recording_path = self.raw_root / "session-subtitle-signal-001" / "recording.mp4"
        recording_path.parent.mkdir(parents=True, exist_ok=True)
        recording_path.write_text("dummy media placeholder", encoding="utf-8")
        append_model(
            self.recording_assets_path,
            RecordingAsset(
                session_id="session-subtitle-signal-001",
                source_type=SourceType.BROWSER_CAPTURE,
                path=str(recording_path),
                started_at=datetime(2026, 4, 26, 9, 0, tzinfo=timezone.utc),
                ended_at=datetime(2026, 4, 26, 9, 30, tzinfo=timezone.utc),
            ),
        )
        service = _FakeSubtitleService(
            self.settings,
            entries=[
                (0.0, 10.0, "Champion select draft begins."),
                (15.0, 25.0, "Game loading now."),
                (40.0, 80.0, "In game scoreboard update."),
                (300.0, 320.0, "Victory game over."),
                (350.0, 360.0, "Another in game cue should not duplicate stage."),
            ],
        )

        service.run()
        signals_path = self.temp_root / "match-stage-signals.jsonl"
        signals = load_models(signals_path, MatchStageSignal)
        self.assertEqual(len(signals), 4)
        self.assertEqual([signal.source for signal in signals], ["subtitles_srt"] * 4)
        self.assertEqual([signal.at_seconds for signal in signals], [0.0, 15.0, 40.0, 300.0])

        service.run()
        signals = load_models(signals_path, MatchStageSignal)
        self.assertEqual(len(signals), 4)

    def test_subtitle_service_filters_by_session_ids_and_match_indices(self) -> None:
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-filter-a",
                match_index=1,
                started_at_seconds=0.0,
                ended_at_seconds=30.0,
                confidence=0.8,
            ),
        )
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-filter-a",
                match_index=2,
                started_at_seconds=30.0,
                ended_at_seconds=60.0,
                confidence=0.8,
            ),
        )
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-filter-b",
                match_index=2,
                started_at_seconds=0.0,
                ended_at_seconds=30.0,
                confidence=0.8,
            ),
        )
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-filter-c",
                match_index=2,
                started_at_seconds=0.0,
                ended_at_seconds=30.0,
                confidence=0.8,
            ),
        )
        settings = self.settings.model_copy(deep=True)
        settings.subtitles.provider = "placeholder"
        service = SubtitleService(settings)

        output = StringIO()
        with redirect_stdout(output):
            service.run(
                session_ids={"session-subtitle-filter-a", "session-subtitle-filter-b"},
                match_indices={2},
            )

        subtitle_assets = _read_jsonl(self.subtitle_assets_path)
        self.assertEqual(len(subtitle_assets), 2)
        self.assertEqual(
            sorted((row["session_id"], row["match_index"]) for row in subtitle_assets),
            [("session-subtitle-filter-a", 2), ("session-subtitle-filter-b", 2)],
        )
        self.assertIn("filters summary total_boundaries=4 matched_boundaries=2", output.getvalue())

    def test_subtitle_service_logs_no_match_when_filters_match_nothing(self) -> None:
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-no-match",
                match_index=1,
                started_at_seconds=0.0,
                ended_at_seconds=30.0,
                confidence=0.8,
            ),
        )
        settings = self.settings.model_copy(deep=True)
        settings.subtitles.provider = "placeholder"
        service = SubtitleService(settings)

        output = StringIO()
        with redirect_stdout(output):
            service.run(
                session_ids={"session-not-exists"},
                match_indices={9},
            )
        self.assertIn("filters summary total_boundaries=1 matched_boundaries=0", output.getvalue())
        self.assertIn("no boundaries matched filters", output.getvalue())
        self.assertIn("processed_matches=0", output.getvalue())
        subtitle_assets = _read_jsonl(self.subtitle_assets_path)
        self.assertEqual(subtitle_assets, [])

    def test_subtitle_service_scopes_auto_stage_signal_ingest_with_same_filters(self) -> None:
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-scope-a",
                match_index=1,
                started_at_seconds=0.0,
                ended_at_seconds=30.0,
                confidence=0.8,
            ),
        )
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-scope-a",
                match_index=2,
                started_at_seconds=30.0,
                ended_at_seconds=60.0,
                confidence=0.8,
            ),
        )
        append_model(
            self.boundaries_path,
            MatchBoundary(
                session_id="session-subtitle-scope-b",
                match_index=2,
                started_at_seconds=0.0,
                ended_at_seconds=30.0,
                confidence=0.8,
            ),
        )
        settings = self.settings.model_copy(deep=True)
        settings.subtitles.provider = "placeholder"
        service = SubtitleService(settings)

        output = StringIO()
        with redirect_stdout(output):
            service.run(
                session_ids={"session-subtitle-scope-a"},
                match_indices={2},
            )
        logs = output.getvalue()
        self.assertIn("filters summary total_boundaries=3 matched_boundaries=1", logs)
        self.assertIn(
            "stage-signals-from-subtitles filter summary total_assets=1 matched_assets=1",
            logs,
        )

        subtitle_assets = _read_jsonl(self.subtitle_assets_path)
        self.assertEqual(
            subtitle_assets,
            [
                {
                    "session_id": "session-subtitle-scope-a",
                    "match_index": 2,
                    "path": str(
                        self.processed_root / "session-subtitle-scope-a" / "match-02.srt"
                    ),
                    "format": "srt",
                }
            ],
        )


if __name__ == "__main__":
    unittest.main()
